basic:
  train: True
  test: False
  finetune: False
  render: False
  process: 1
  path: ''
  model_id: 0
  seed: 42
  env_name: ???
  alg: td3
env:
  name: ${..basic.env_name}

  task: ${.raw_env_cfg.task}
  sim_device: ${.raw_env_cfg.sim_device}
  graphics_device_id: ${.raw_env_cfg.graphics_device_id}
  headless: ${if:${..basic.render},False,True}